import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Locale = "zh-CN" | "en-US";
const messages = {
  "zh-CN": {tagline:"资料里的好故事，值得被听见",heroLead:"把你的资料，",heroEmphasis:"锻造成播客。",heroCopy:"上传 PDF、DOCX、TXT 或 Markdown，几分钟内获得一场自然、有重点的中文双人对谈。",selectFiles:"选择资料",selectFilesCopy:"单个文件最大 10 MB，可同时上传多个",dropFiles:"拖放文件到这里",browseFiles:"或点击浏览本地文件",customize:"定制节目",customizeCopy:"为这期节目设置声音方向",podcastTitle:"播客标题",titlePlaceholder:"例如：重新理解人工智能",targetLanguage:"目标语言",targetDuration:"目标时长",podcastStyle:"节目风格",createPodcast:"开始生成播客",createError:"创建任务失败",chinese:"简体中文",english:"English",minutes:(value:number)=>`约 ${value} 分钟`,casual:"轻松科普",interview:"深度访谈",news:"新闻解读",storytelling:"故事叙述",emptyTitle:"你的节目将在这里诞生",emptyCopy:"上传资料并设置节目参数，生成进度与成品会实时显示。",failedEyebrow:"生成未完成",failedTitle:"这次锻造遇到了问题",retry:"重试生成",edit:"返回修改资料",completedEyebrow:"新鲜出炉",download:"下载 MP3 ↓",script:"查看完整脚本",host:"主持人",guest:"嘉宾",working:"正在制作",progressHint:"可以保存此页面地址，刷新后任务仍会继续。",languageLabel:"页面语言",zhShort:"中",enShort:"EN"},
  "en-US": {tagline:"Great stories in your files deserve to be heard",heroLead:"Turn your source material",heroEmphasis:"into a podcast.",heroCopy:"Upload PDF, DOCX, TXT, or Markdown files and get a natural, focused two-person conversation in minutes.",selectFiles:"Choose files",selectFilesCopy:"Up to 10 MB per file; multiple files supported",dropFiles:"Drop files here",browseFiles:"or click to browse",customize:"Customize your show",customizeCopy:"Set the direction for this episode",podcastTitle:"Podcast title",titlePlaceholder:"e.g. Rethinking Artificial Intelligence",targetLanguage:"Podcast language",targetDuration:"Target length",podcastStyle:"Show style",createPodcast:"Generate podcast",createError:"Could not create the job",chinese:"Simplified Chinese",english:"English",minutes:(value:number)=>`About ${value} minutes`,casual:"Accessible explainer",interview:"In-depth interview",news:"News analysis",storytelling:"Narrative storytelling",emptyTitle:"Your show will take shape here",emptyCopy:"Upload your material and choose the show settings. Progress and the finished episode will appear here.",failedEyebrow:"Generation incomplete",failedTitle:"We hit a problem while creating your show",retry:"Try again",edit:"Edit source material",completedEyebrow:"Fresh from the studio",download:"Download MP3 ↓",script:"View full transcript",host:"Host",guest:"Guest",working:"In production",progressHint:"Save this page URL—your job will continue even if you refresh.",languageLabel:"Page language",zhShort:"中",enShort:"EN"},
};
export type Messages = typeof messages["zh-CN"];
const LocaleContext = createContext<{locale:Locale;setLocale:(locale:Locale)=>void;t:Messages}|null>(null);
function browserLocale():Locale{const saved=localStorage.getItem("podforge-locale");if(saved==="zh-CN"||saved==="en-US")return saved;return navigator.language.toLowerCase().startsWith("zh")?"zh-CN":"en-US"}
export function I18nProvider({children}:{children:ReactNode}){const [locale,setLocale]=useState<Locale>(browserLocale);useEffect(()=>{document.documentElement.lang=locale;localStorage.setItem("podforge-locale",locale)},[locale]);const value=useMemo(()=>({locale,setLocale,t:messages[locale] as Messages}),[locale]);return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>}
export function useI18n(){const value=useContext(LocaleContext);if(!value)throw new Error("useI18n must be used inside I18nProvider");return value}
const stages:Record<Locale,Record<string,string>>={"zh-CN":{},"en-US":{"等待处理":"Waiting to start","等待重试":"Waiting to retry","正在生成双人脚本":"Writing the two-person script","生成完成":"Generation complete","生成失败":"Generation failed"}};
export const translateStage=(stage:string,locale:Locale)=>stages[locale][stage]??stage;
