import { useRef,useState,type DragEvent } from "react";import { useI18n } from "../i18n";
type Props={onCreate:(data:FormData)=>Promise<void>};
export function JobForm({onCreate}:Props){const {locale,t}=useI18n(),[files,setFiles]=useState<File[]>([]),[title,setTitle]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[dragging,setDragging]=useState(false),input=useRef<HTMLInputElement>(null),titleEdited=useRef(false);function updateFiles(nextFiles:File[]){setFiles(nextFiles);if(!titleEdited.current){setTitle(currentTitle=>currentTitle||getFileTitle(nextFiles[0]))}}function handleDrag(event:DragEvent<HTMLLabelElement>){event.preventDefault();event.stopPropagation();if(event.type==="dragenter"||event.type==="dragover"){event.dataTransfer.dropEffect="copy";setDragging(true)}else{setDragging(false)}}function handleDrop(event:DragEvent<HTMLLabelElement>){event.preventDefault();event.stopPropagation();setDragging(false);updateFiles([...event.dataTransfer.files])}async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");setBusy(true);try{const data=new FormData(event.currentTarget);files.forEach(file=>data.append("files",file));await onCreate(data)}catch(cause){setError(cause instanceof Error?cause.message:t.createError)}finally{setBusy(false)}}return <form className="card" onSubmit={submit}>
  <Step number="01" title={t.selectFiles} copy={t.selectFilesCopy}/>
  <label className={`dropzone${dragging?" drag":""}`} onDragEnter={handleDrag} onDragOver={handleDrag} onDragLeave={handleDrag} onDrop={handleDrop}><input ref={input} type="file" multiple accept=".pdf,.docx,.txt,.md,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,text/markdown" onChange={e=>updateFiles([...e.target.files??[]])}/><span className="upload-icon">↑</span><strong>{t.dropFiles}</strong><small>{t.browseFiles}</small></label>
  <ul className="file-list" aria-live="polite">{files.map(file=><li key={`${file.name}-${file.size}`}>{file.name}<span>{(file.size/1048576).toFixed(1)} MB</span></li>)}</ul>
  <Step number="02" title={t.customize} copy={t.customizeCopy}/>
  <label>{t.podcastTitle}<input name="title" value={title} maxLength={120} placeholder={t.titlePlaceholder} required onChange={event=>{titleEdited.current=true;setTitle(event.target.value)}}/></label>
  <div className="fields"><label>{t.targetLanguage}<select name="language" defaultValue={locale}><option value="zh-CN">{t.chinese}</option><option value="en-US">{t.english}</option></select></label><label>{t.targetDuration}<select name="duration" defaultValue="8">{[5,8,15,30].map(value=><option value={value} key={value}>{t.minutes(value)}</option>)}</select></label></div>
  <label>{t.podcastStyle}<select name="style"><option value="轻松科普">{t.casual}</option><option value="深度访谈">{t.interview}</option><option value="新闻解读">{t.news}</option><option value="故事叙述">{t.storytelling}</option></select></label>
  <button id="submit" disabled={busy||files.length===0}>{t.createPodcast} <span>→</span></button><p className="error" role="alert">{error}</p>
 </form>}
function getFileTitle(file?:File){if(!file)return "";const extensionIndex=file.name.lastIndexOf(".");return (extensionIndex>0?file.name.slice(0,extensionIndex):file.name).slice(0,120)}
function Step({number,title,copy}:{number:string;title:string;copy:string}){return <div className="step"><b>{number}</b><div><h2>{title}</h2><p>{copy}</p></div></div>}
